// @ts-nocheck
declare const styles = {
  'noscript': '' as readonly string,
  'jsError': '' as readonly string,
  'formElement': '' as readonly string,
  'list': '' as readonly string,
  'listItem': '' as readonly string,
  'formContainer': '' as readonly string,
  'formContainer': '' as readonly string,
  'formContainer': '' as readonly string,
  'formContainer': '' as readonly string,
  'stepContainer': '' as readonly string,
  'label': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'input': '' as readonly string,
  'cssProperty': '' as readonly string,
  'input': '' as readonly string,
  'flexWrapJoiner': '' as readonly string,
  'select': '' as readonly string,
  'select': '' as readonly string,
  'select': '' as readonly string,
  'output': '' as readonly string,
  'output': '' as readonly string,
  'notification': '' as readonly string,
  'notification': '' as readonly string,
  'kbd': '' as readonly string,
  'result': '' as readonly string,
};
export default styles;
