import type { FC } from 'react'
import { useEffect } from 'react'
import styles from './Unorphan.module.css'
import { unorphan } from '../../scripts/unorphan'

// https://news.ycombinator.com/item?id=43497719
export const Unorphan: FC = () => {
	useEffect(() => {
		const unorphanOptions = {
			resize: true,
			resizeThrottleDelay: 250,
			onUnorphan: () => {
				/* TODO: automatically create voiceover accessible headings (AFTER unorphaning) */
			},
			force: false,
		}
		unorphan(window.document.querySelectorAll('h1, h2, h3, h4, h5, h6, p, li, th, td'), unorphanOptions)
	}, [])

	return (
		// TODO: this entire div should be generated by unorphan, so that it can be extracted into a separate npm package
		<div className={styles.offscreen} id="offscreen">
			<div className={styles.offscreenReveal} id="offscreen-reveal"></div>
			<div className={styles.offscreenNowrap} id="offscreen-nowrap"></div>
		</div>
	)
}
