import type { FunctionalComponent } from 'preact'
import { useEffect } from 'preact/hooks'
import classes from './Unorphan.module.css'
import { unorphan } from '../../scripts/unorphan'

export const Unorphan: FunctionalComponent = () => {
	useEffect(() => {
		const unorphanOptions = {
			resize: true,
			resizeThrottleDelay: 250,
			onUnorphan: () => {
				/* TODO: automatically create voiceover accessible headings (AFTER unorphaning) */
			},
			force: false,
		}
		unorphan(window.document.querySelectorAll('h1, h2, h3, h4, h5, h6, p, li, th, td'), unorphanOptions)
	}, [])

	return (
		// TODO: this entire div should be generated by unorphan, so that it can be extracted into a separate npm package
		<div class={classes.offscreen} id="offscreen">
			<div class={classes.offscreenReveal} id="offscreen-reveal"></div>
			<div class={classes.offscreenNowrap} id="offscreen-nowrap"></div>
		</div>
	)
}
