// @ts-check

const camelCase = '^[a-z][a-zA-Z0-9]*$' // css-modules-kit doesn't support kebab-case: https://github.com/mizdra/css-modules-kit/issues/251
const muiCssCustomPropertyPattern = '^([_a-z][a-z0-9]*)(-[a-z0-9]+)*(-[a-z][a-zA-Z0-9]*)?$'

/** @type {import('stylelint').Config} */
const stylelintConfig = {
	rules: {
		'at-rule-no-deprecated': true,
		'declaration-property-value-keyword-no-deprecated': true,
		'media-type-no-deprecated': true,
		'property-no-deprecated': true,
		'no-descending-specificity': true,
		'declaration-block-no-duplicate-custom-properties': true,
		'declaration-block-no-duplicate-properties': true,
		'font-family-no-duplicate-names': true,
		'keyframe-block-no-duplicate-selectors': true,
		'no-duplicate-at-import-rules': true,
		'no-duplicate-selectors': true,
		'block-no-empty': true,
		'comment-no-empty': true,
		'no-empty-source': true,
		'at-rule-prelude-no-invalid': true,
		'color-no-invalid-hex': null,
		'function-calc-no-unspaced-operator': true,
		'keyframe-declaration-no-important': true,
		'media-query-no-invalid': true,
		'named-grid-areas-no-invalid': true,
		'no-invalid-double-slash-comments': true,
		'no-invalid-position-at-import-rule': true,
		'no-invalid-position-declaration': true,
		'string-no-newline': true,
		'syntax-string-no-invalid': true,
		'no-irregular-whitespace': true,
		'custom-property-no-missing-var-function': true,
		'font-family-no-missing-generic-family-keyword': true,
		'nesting-selector-no-missing-scoping-root': true,
		'function-linear-gradient-no-nonstandard-direction': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'selector-anb-no-unmatchable': true,
		'annotation-no-unknown': true,
		'at-rule-descriptor-no-unknown': true,
		'at-rule-descriptor-value-no-unknown': true,
		'at-rule-no-unknown': true,
		'declaration-property-value-no-unknown': true,
		'function-no-unknown': true,
		'media-feature-name-no-unknown': true,
		'media-feature-name-value-no-unknown': true,
		'no-unknown-animations': true,
		'no-unknown-custom-media': true,
		'no-unknown-custom-properties': null, // because of MUI
		'property-no-unknown': true,
		'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['global'] }],
		'selector-pseudo-element-no-unknown': true,
		'selector-type-no-unknown': true,
		'unit-no-unknown': null,
		'at-rule-allowed-list': null,
		'at-rule-disallowed-list': [],
		'at-rule-no-vendor-prefix': true,
		'at-rule-property-required-list': {
			'font-face': ['font-display', 'font-family', 'font-weight', 'font-style', 'src'],
		},
		'color-hex-alpha': null,
		'color-named': 'always-where-possible',
		'color-no-hex': true,
		'comment-word-disallowed-list': null,
		// 'declaration-no-important': true, // TODO: investigate css module import order in next.js app and ensure it's always consistent (or figure out a way to enforce consistency) and then enable this rule
		'declaration-property-unit-allowed-list': [{ 'font-size': ['rem'], 'line-height': [] }],
		'declaration-property-unit-disallowed-list': null,
		'declaration-property-value-allowed-list': null,
		'declaration-property-value-disallowed-list': [{ 'line-height': 'normal' }],
		'function-allowed-list': null,
		'function-disallowed-list': [],
		'function-url-no-scheme-relative': true,
		'function-url-scheme-allowed-list': ['data', '/^http/'],
		'function-url-scheme-disallowed-list': null,
		'length-zero-no-unit': true,
		'media-feature-name-allowed-list': null,
		'media-feature-name-disallowed-list': ['max-width'],
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-name-unit-allowed-list': null,
		'media-feature-name-value-allowed-list': null,
		'property-allowed-list': null,
		'property-disallowed-list': [],
		'property-no-vendor-prefix': true,
		'rule-nesting-at-rule-required-list': null,
		'rule-selector-property-disallowed-list': null,
		'selector-attribute-name-disallowed-list': null,
		'selector-attribute-operator-allowed-list': null,
		'selector-attribute-operator-disallowed-list': null,
		'selector-combinator-allowed-list': null,
		'selector-combinator-disallowed-list': null,
		'selector-disallowed-list': null,
		'selector-no-qualifying-type': null,
		'selector-no-vendor-prefix': true,
		'selector-pseudo-class-allowed-list': null,
		'selector-pseudo-class-disallowed-list': [],
		'selector-pseudo-element-allowed-list': null,
		'selector-pseudo-element-disallowed-list': [],
		'unit-allowed-list': null,
		'unit-disallowed-list': ['cm', 'mm', 'Q', 'in', 'pc', 'pt', 'vw', 'vh', 'vmin', 'vmax'],
		'value-no-vendor-prefix': true,
		'function-name-case': 'lower',
		'selector-type-case': 'lower',
		'value-keyword-case': 'lower',
		'at-rule-empty-line-before': null,
		'comment-empty-line-before': null,
		'custom-property-empty-line-before': [
			'always',

			{ except: ['after-comment'], ignore: ['after-custom-property', 'first-nested'] },
		],
		'declaration-empty-line-before': [
			'always',
			{ ignore: ['after-comment', 'after-declaration', 'first-nested', 'inside-single-line-block'] },
		],
		'rule-empty-line-before': [
			'always',
			{ except: ['after-single-line-comment'], ignore: ['after-comment', 'first-nested'] },
		],
		'declaration-block-single-line-max-declarations': null,
		'declaration-property-max-values': null,
		'max-nesting-depth': null,
		'number-max-precision': 3,
		'selector-max-attribute': null,
		'selector-max-class': null,
		'selector-max-combinators': null,
		'selector-max-compound-selectors': null,
		'selector-max-id': null,
		'selector-max-pseudo-class': null,
		'selector-max-specificity': null,
		'selector-max-type': null,
		'selector-max-universal': null,
		'time-min-milliseconds': null,
		'alpha-value-notation': 'percentage',
		'color-function-alias-notation': 'without-alpha',
		'color-function-notation': 'modern',
		'color-hex-length': null,
		'font-weight-notation': 'named-where-possible', // normal === 400 and bold === 700
		'hue-degree-notation': 'angle',
		'import-notation': 'url',
		'keyframe-selector-notation': 'percentage-unless-within-keyword-only-block',
		'lightness-notation': 'percentage',
		'media-feature-range-notation': 'context',
		'selector-not-notation': null,
		'selector-pseudo-element-colon-notation': 'double',
		'comment-pattern': null,
		'container-name-pattern': null,
		'custom-media-pattern': null,
		'custom-property-pattern': `(${camelCase})|(${muiCssCustomPropertyPattern})`,
		'keyframes-name-pattern': camelCase,
		'layer-name-pattern': camelCase,
		'selector-class-pattern': `(^Mui.*-.+|${camelCase})`,
		'selector-id-pattern': camelCase,
		'selector-nested-pattern': null,
		'font-family-name-quotes': 'always-unless-keyword',
		'function-url-quotes': ['always', { except: ['empty'] }],
		'selector-attribute-quotes': 'always',
		'block-no-redundant-nested-style-rules': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'shorthand-property-no-redundant-values': true,
		'comment-whitespace-inside': 'always',
	},
	reportDescriptionlessDisables: true,
	reportInvalidScopeDisables: true,
	reportNeedlessDisables: true,
	reportUnscopedDisables: true,
}

export default stylelintConfig
