declare const styles:
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "ol": string }>
  & Readonly<{ "li": string }>
;
export default styles;
//# sourceMappingURL=./TableOfContents.module.d.css.ts.map
